org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

archives_base_name=morevillagers
mod_version=6.0.0
maven_group=com.samebutdifferent

fabric_loader_version=0.18.4
fabric_api_version=0.116.8+1.21.1
cloth_fabric_version=15.0.140
modmenu_version=11.0.3

neoforged_version=21.1.218
