org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.11
enabled_platforms=fabric,neoforge

archives_base_name=morevillagers
mod_version=7.0.0
maven_group=com.samebutdifferent

fabric_loader_version=0.18.4
fabric_api_version=0.141.2+1.21.11
cloth_fabric_version=21.11.153
modmenu_version=17.0.0-beta.2

neoforged_version=21.11.37-beta
