org.gradle.jvmargs=-Xmx3G

minecraft_version=26.2
enabled_platforms=fabric,neoforge

archives_base_name=morevillagers
mod_version=8.1.0
maven_group=com.samebutdifferent

fabric_loader_version=0.19.3
fabric_api_version=0.154.2+26.2
cloth_fabric_version=26.2.155
modmenu_version=20.0.0

neoforged_version=26.2.0.8-beta
